### ISSUE TITLE
I cannot pass an ENV variable to the thing running

### ISSUE THREAD

**Issue by jessfraz** [CodSpeedHQ/runner#70]
our benchmarks require an API token. This is usually done via an env variable. I cannot seem to get this to pass thru correctly.

ive tried using the github action like:
```
uses: CodSpeedHQ/action@v3
        with:
          working-directory: rust
          run: cargo codspeed run
          token: ${{ secrets.CODSPEED_TOKEN }}
        env:
          KITTYCAD_API_TOKEN: ${{ secrets.KITTYCAD_API_TOKEN }}
```

and 

```
uses: CodSpeedHQ/action@v3
        with:
          working-directory: rust
          run: KITTYCAD_API_TOKEN=${{ secrets.KITTYCAD_API_TOKEN }} cargo codspeed run
          token: ${{ secrets.CODSPEED_TOKEN }}
```

nothing works

**Comment by art049** [comment]
We added some tests both in [the GitHub action](https://github.com/CodSpeedHQ/action/commit/b82c12733976f190b6c5f8497341ba1c88c08f37) and in [cargo-codspeed](https://github.com/CodSpeedHQ/codspeed-rust/pull/89/commits/803ed66ee374ecb6ca75f65b04c09d0e298e7c09). Env variables are passed at runtime as expected.

Feel free to reopen with a minimal reproduction.

**Comment by art049** [comment]
Like this:
```yaml
      - name: Run the benchmarks
        uses: CodSpeedHQ/action@main
        env:
          MY_ENV_VAR: "YES"
        with:
          run: cargo codspeed run
          token: ${{ secrets.CODSPEED_TOKEN }}
```
And then it's picked up:
https://github.com/CodSpeedHQ/codspeed-rust/actions/runs/13808282274/job/38623721638#step:10:172
